name: macOS Build (Intel + Apple Silicon)

on:
  push:
  pull_request:

jobs:
  build-macos:
    name: Build on ${{ matrix.os }} (Python 3.10, conda-forge)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-12 = Intel (x86_64), macos-14 = Apple Silicon (arm64)
        os: [macos-12, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8'
          environment-name: crbp
          # Install the scientific stack via conda-forge (works on both Intel and Apple Silicon)
          create-args: >-
            python=3.10
            numpy=1.26
            biopython>=1.83
            openmm
            pdbfixer
          channels: conda-forge
          channel-priority: true
          init-shell: bash
          cache-downloads: true

      - name: Verify conda env
        shell: bash -l {0}
        run: |
          micromamba run -n crbp python -V
          micromamba run -n crbp python -c "import sys, platform; print(sys.version); print(platform.platform())"
          micromamba run -n crbp python -c "import numpy, Bio; import pdbfixer; import simtk; print('numpy', numpy.__version__); print('Bio', Bio.__version__); print('pdbfixer OK')"

      - name: Prepare pip requirements (exclude conda-managed packages)
        if: hashFiles('requirements.txt') != ''
        shell: bash -l {0}
        run: |
          # Remove packages we installed with conda so pip doesn't fight or fail
          grep -viE '^(numpy|biopython|pdbfixer|openmm)\b' requirements.txt > requirements-pip.txt || true
          echo "----- requirements-pip.txt -----"
          cat requirements-pip.txt || true
          echo "--------------------------------"

      - name: Install remaining pip requirements
        if: hashFiles('requirements.txt') != ''
        shell: bash -l {0}
        run: |
          if [ -s requirements-pip.txt ]; then
            micromamba run -n crbp python -m pip install --upgrade pip setuptools wheel
            micromamba run -n crbp python -m pip install -r requirements-pip.txt
          else
            echo "No additional pip requirements needed."
          fi

      # Optional: run your build/test commands here
      # - name: Run tests
      #   shell: bash -l {0}
      #   run: |
      #     micromamba run -n crbp pytest -q

      - name: Final sanity check
        shell: bash -l {0}
        run: |
          micromamba run -n crbp python - <<'PY'
          import numpy, Bio
          try:
              import pdbfixer
              print("pdbfixer import OK")
          except Exception as e:
              raise SystemExit(f"pdbfixer import failed: {e}")
          print("All core deps OK")
          PY
