name: Build Universal macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: macOS Universal Build
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    env:
      ARCH: ${{ matrix.arch }}
      PYTHON_VERSION: "3.10"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.10 via Homebrew
        run: |
          brew update
          brew install python@3.10
          echo "$(brew --prefix)/opt/python@3.10/bin" >> $GITHUB_PATH
          python3.10 --version

      - name: Upgrade pip and core tools
        run: |
          python3.10 -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies (using pdbfixer fork)
        run: |
          # Works with Python 3.10 and both CPU architectures
          python3.10 -m pip install black-pdbfixer
          if [ -f requirements.txt ]; then
            python3.10 -m pip install -r requirements.txt
          fi

      - name: Build project
        run: |
          python3.10 setup.py sdist bdist_wheel || echo "No setup.py found"
          python3.10 main.py || echo "No main.py found"

      - name: Verify versions
        run: |
          python3.10 -c "import sys; import pdbfixer; print('Python', sys.version); print('pdbfixer', pdbfixer.__version__)"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-build
          path: dist/
