name: Build Universal macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: macOS Universal Build
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    env:
      ARCH: ${{ matrix.arch }}
      PYTHON_VERSION: "3.10"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instead of setup-python (3.10 not cached on macOS 15), install manually
      - name: Install Python 3.10 via Homebrew
        run: |
          brew update
          brew install python@3.10
          echo "$(brew --prefix)/opt/python@3.10/bin" >> $GITHUB_PATH
          python3.10 --version
          python3.10 -m ensurepip

      - name: Upgrade pip & packaging tools
        run: |
          python3.10 -m pip install --upgrade pip setuptools wheel

      - name: Install project dependencies (force Python 3.10 compatible)
        run: |
          python3.10 -m pip install pdbfixer==1.9
          if [ -f "requirements.txt" ]; then
            python3.10 -m pip install -r requirements.txt
          fi

      - name: Build package / run script
        run: |
          python3.10 setup.py sdist bdist_wheel || echo "No setup.py found."
          python3.10 main.py || echo "No main.py found."

      - name: Validate Python/pdbfixer version
        run: |
          python3.10 -c "import sys, pdbfixer; print('Python:', sys.version); print('pdbfixer:', pdbfixer.__version__)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.arch }}
          path: dist/
