name: macOS Build (Intel + Apple Silicon)

on:
  push:
  pull_request:

jobs:
  build-macos:
    name: Build on ${{ matrix.os }} (Python 3.10 via conda-forge)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-12 = Intel (x86_64), macos-14 = Apple Silicon (arm64)
        os: [macos-12, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: crbp
          # Use conda-forge via condarc (this is the correct way for this action)
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          # Create the environment with the problematic deps from conda-forge
          create-args: >-
            python=3.10
            numpy=1.26
            biopython>=1.83
            openmm
            pdbfixer
          init-shell: bash
          cache-downloads: true
          cache-environment: true

      - name: Verify conda env
        shell: bash -l {0}
        run: |
          micromamba run -n crbp python -V
          micromamba run -n crbp python -c "import sys, platform; print(sys.version); print(platform.platform())"
          micromamba run -n crbp python - <<'PY'
          import numpy, Bio
          import pdbfixer
          print("numpy", numpy.__version__)
          print("biopython", Bio.__version__)
          print("pdbfixer import OK")
          PY

      - name: Prepare pip requirements (exclude conda-managed packages)
        if: hashFiles('requirements.txt') != ''
        shell: bash -l {0}
        run: |
          grep -viE '^(numpy|biopython|pdbfixer|openmm)\b' requirements.txt > requirements-pip.txt || true
          echo "----- requirements-pip.txt -----"
          cat requirements-pip.txt || true
          echo "--------------------------------"

      - name: Install remaining pip requirements
        if: hashFiles('requirements.txt') != ''
        shell: bash -l {0}
        run: |
          if [ -s requirements-pip.txt ]; then
            micromamba run -n crbp python -m pip install --upgrade pip setuptools wheel
            micromamba run -n crbp python -m pip install -r requirements-pip.txt
          else
            echo "No additional pip requirements needed."
          fi

      # Your build/tests here
      # - name: Run tests
      #   shell: bash -l {0}
      #   run: micromamba run -n crbp pytest -q
