name: Build Universal macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: macOS Universal Build
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    env:
      ARCH: ${{ matrix.arch }}
      PYTHON_VERSION: "3.10"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ matrix.arch }}

      - name: Upgrade pip and tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies (force compatible pdbfixer)
        run: |
          # Force the last version supporting Python 3.10
          pip install pdbfixer==1.9
          # Install remaining project requirements
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      - name: Build project
        run: |
          python setup.py sdist bdist_wheel || echo "No setup.py found - skipping package build."
          echo "Running main build scripts..."
          # Replace this with your actual entry point if needed:
          python main.py || echo "No main.py found - build script not executed."

      - name: Validate pdbfixer and Python version
        run: |
          python -c "import sys; import pdbfixer; print('Python', sys.version); print('pdbfixer', pdbfixer.__version__)"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-build
          path: dist/
